name: Catalogue Application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  compile:
    runs-on: workstation
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'

    - name: Compile & Build
      run: npm install

    - name: Upload Node Modules artifact
      uses: actions/upload-artifact@v4
      with:
        name: app
